package co.zero.geekalgorithm.datastructures.arrays;

import java.util.Arrays;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.function.Function;
import java.util.stream.Collectors;

public class SparseArray {
    
    public static int[] matchingStrings(String[] strings, String[] queries) {
        Map<String, Integer> queryHash = Arrays.stream(queries)
                .collect(Collectors.toMap(Function.identity(), query -> 0, (key1, key2) -> key1, LinkedHashMap::new));
        
        for (String word : strings) {
            if (queryHash.containsKey(word)) {
                queryHash.put(word, queryHash.get(word) + 1);
            }
        }
    
        return Arrays.stream(queries)
                .mapToInt(query -> queryHash.get(query))
                .toArray();
    }
    
    public static void main(String[] args) {
        String[] a1 = new String[]{"aba", "baba", "aba", "xzxb"};
        String[] a2 = new String[]{"aba", "xzxb","ab"};
        String[] b1 = new String[]{"def", "de", "fgh"};
        String[] b2 = new String[]{"de","lmn","fgh"};
        String[] c1 = new String[]{"abcde", "sdaklfj", "asdjf", "na", "basdn", "sdaklfj", "asdjf",
                "na", "asdjf", "na", "basdn", "sdaklfj", "asdjf"};
        String[] c2 = new String[]{"abcde", "sdaklfj", "asdjf", "na", "basdn"};
        
        String[] d1 = new String[]{"lekgdisnsbfdzpqlkg",
                "eagemhdygyv",
                "jwvwwnrhuai",
                "urcadmrwlqe",
                "mpgqsvxrijpombyv",
                "mpgqsvxrijpombyv",
                "urcadmrwlqe",
                "mpgqsvxrijpombyv",
                "eagemhdygyv",
                "eagemhdygyv",
                "jwvwwnrhuai",
                "urcadmrwlqe",
                "jwvwwnrhuai",
                "kvugevicpsdf",
                "kvugevicpsdf",
                "mpgqsvxrijpombyv",
                "urcadmrwlqe",
                "mpgqsvxrijpombyv",
                "exdafbnobg",
                "qhootohpnfvbl",
                "suffrbmqgnln",
                "exdafbnobg",
                "exdafbnobg",
                "eagemhdygyv",
                "mpgqsvxrijpombyv",
                "urcadmrwlqe",
                "jwvwwnrhuai",
                "lekgdisnsbfdzpqlkg",
                "mpgqsvxrijpombyv",
                "lekgdisnsbfdzpqlkg",
                "jwvwwnrhuai",
                "exdafbnobg",
                "mpgqsvxrijpombyv",
                "kvugevicpsdf",
                "qhootohpnfvbl",
                "urcadmrwlqe",
                "kvugevicpsdf",
                "mpgqsvxrijpombyv",
                "lekgdisnsbfdzpqlkg",
                "mpgqsvxrijpombyv",
                "kvugevicpsdf",
                "qhootohpnfvbl",
                "lxyqetmgdbmh",
                "urcadmrwlqe",
                "urcadmrwlqe",
                "kvugevicpsdf",
                "lxyqetmgdbmh",
                "urcadmrwlqe",
                "lxyqetmgdbmh",
                "jwvwwnrhuai",
                "qhootohpnfvbl",
                "qhootohpnfvbl",
                "jwvwwnrhuai",
                "lekgdisnsbfdzpqlkg",
                "kvugevicpsdf",
                "mpgqsvxrijpombyv",
                "exdafbnobg",
                "kvugevicpsdf",
                "lekgdisnsbfdzpqlkg",
                "qhootohpnfvbl",
                "exdafbnobg",
                "qhootohpnfvbl",
                "exdafbnobg",
                "mpgqsvxrijpombyv",
                "suffrbmqgnln",
                "mpgqsvxrijpombyv",
                "qhootohpnfvbl",
                "jwvwwnrhuai",
                "mpgqsvxrijpombyv",
                "qhootohpnfvbl",
                "lekgdisnsbfdzpqlkg",
                "eagemhdygyv",
                "jwvwwnrhuai",
                "kvugevicpsdf",
                "eagemhdygyv",
                "eagemhdygyv",
                "lxyqetmgdbmh",
                "qhootohpnfvbl",
                "lxyqetmgdbmh",
                "exdafbnobg",
                "qhootohpnfvbl",
                "qhootohpnfvbl",
                "exdafbnobg",
                "suffrbmqgnln",
                "mpgqsvxrijpombyv",
                "urcadmrwlqe",
                "eagemhdygyv",
                "lxyqetmgdbmh",
                "urcadmrwlqe",
                "suffrbmqgnln",
                "qhootohpnfvbl",
                "kvugevicpsdf",
                "lekgdisnsbfdzpqlkg",
                "lxyqetmgdbmh",
                "mpgqsvxrijpombyv",
                "jwvwwnrhuai",
                "lxyqetmgdbmh",
                "lxyqetmgdbmh",
                "lekgdisnsbfdzpqlkg",
                "qhootohpnfvbl"};
        String[] d2 = new String[]{
                "exdafbnobg",
                "eagemhdygyv",
                "mpgqsvxrijpombyv",
                "kvugevicpsdf",
                "lekgdisnsbfdzpqlkg",
                "kvugevicpsdf",
                "exdafbnobg",
                "qhootohpnfvbl",
                "eagemhdygyv",
                "kvugevicpsdf",
                "suffrbmqgnln",
                "jwvwwnrhuai",
                "lekgdisnsbfdzpqlkg",
                "lekgdisnsbfdzpqlkg",
                "mpgqsvxrijpombyv",
                "jwvwwnrhuai",
                "kvugevicpsdf",
                "lekgdisnsbfdzpqlkg",
                "exdafbnobg",
                "suffrbmqgnln",
                "qhootohpnfvbl",
                "eagemhdygyv",
                "exdafbnobg",
                "suffrbmqgnln",
                "jwvwwnrhuai",
                "qhootohpnfvbl",
                "eagemhdygyv",
                "exdafbnobg",
                "exdafbnobg",
                "jwvwwnrhuai",
                "qhootohpnfvbl",
                "lxyqetmgdbmh",
                "qhootohpnfvbl",
                "suffrbmqgnln",
                "lxyqetmgdbmh",
                "qhootohpnfvbl",
                "eagemhdygyv",
                "jwvwwnrhuai",
                "eagemhdygyv",
                "qhootohpnfvbl",
                "mpgqsvxrijpombyv",
                "qhootohpnfvbl",
                "jwvwwnrhuai",
                "exdafbnobg",
                "eagemhdygyv",
                "eagemhdygyv",
                "kvugevicpsdf",
                "kvugevicpsdf",
                "jwvwwnrhuai",
                "urcadmrwlqe",
                "lxyqetmgdbmh",
                "qhootohpnfvbl",
                "exdafbnobg",
                "exdafbnobg",
                "eagemhdygyv",
                "qhootohpnfvbl",
                "exdafbnobg",
                "exdafbnobg",
                "lekgdisnsbfdzpqlkg",
                "jwvwwnrhuai",
                "eagemhdygyv",
                "urcadmrwlqe",
                "kvugevicpsdf",
                "lekgdisnsbfdzpqlkg",
                "jwvwwnrhuai",
                "eagemhdygyv",
                "lekgdisnsbfdzpqlkg",
                "exdafbnobg",
                "kvugevicpsdf",
                "jwvwwnrhuai",
                "exdafbnobg",
                "lxyqetmgdbmh",
                "exdafbnobg",
                "lxyqetmgdbmh",
                "jwvwwnrhuai",
                "mpgqsvxrijpombyv",
                "eagemhdygyv",
                "urcadmrwlqe",
                "kvugevicpsdf",
                "qhootohpnfvbl",
                "jwvwwnrhuai",
                "eagemhdygyv",
                "urcadmrwlqe",
                "urcadmrwlqe",
                "exdafbnobg",
                "qhootohpnfvbl",
                "exdafbnobg",
                "eagemhdygyv",
                "exdafbnobg",
                "jwvwwnrhuai",
                "eagemhdygyv",
                "jwvwwnrhuai",
                "mpgqsvxrijpombyv",
                "urcadmrwlqe",
                "urcadmrwlqe",
                "eagemhdygyv",
                "eagemhdygyv",
                "jwvwwnrhuai",
                "suffrbmqgnln",
                "eagemhdygyv"
        };
        int[] answer = matchingStrings(a1, a2);
        System.out.println("Arrays.toString(answer) = " + Arrays.toString(answer));
        answer = matchingStrings(b1, b2);
        System.out.println("Arrays.toString(answer) = " + Arrays.toString(answer));
        answer = matchingStrings(c1, c2);
        System.out.println("Arrays.toString(answer) = " + Arrays.toString(answer));
        answer = matchingStrings(d1, d2);
        System.out.println("Arrays.toString(answer) = " + Arrays.toString(answer));
    }
}
